// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_get_post is a generated GoMock package.
package mock_get_post

import (
	get_post "postservice/internal/features/get_post"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetPresignedUrlsForDownloading mocks base method.
func (m *MockRepository) GetPresignedUrlsForDownloading(data []*get_post.Post) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedUrlsForDownloading", data)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedUrlsForDownloading indicates an expected call of GetPresignedUrlsForDownloading.
func (mr *MockRepositoryMockRecorder) GetPresignedUrlsForDownloading(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedUrlsForDownloading", reflect.TypeOf((*MockRepository)(nil).GetPresignedUrlsForDownloading), data)
}

// GetUserPostMetadatas mocks base method.
func (m *MockRepository) GetUserPostMetadatas(username string) ([]*get_post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPostMetadatas", username)
	ret0, _ := ret[0].([]*get_post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPostMetadatas indicates an expected call of GetUserPostMetadatas.
func (mr *MockRepositoryMockRecorder) GetUserPostMetadatas(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPostMetadatas", reflect.TypeOf((*MockRepository)(nil).GetUserPostMetadatas), username)
}
