// Code generated by MockGen. DO NOT EDIT.
// Source: object_storage.go

// Package mock_objectstorage is a generated GoMock package.
package mock_objectstorage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockObjectStorageClient is a mock of ObjectStorageClient interface.
type MockObjectStorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageClientMockRecorder
}

// MockObjectStorageClientMockRecorder is the mock recorder for MockObjectStorageClient.
type MockObjectStorageClientMockRecorder struct {
	mock *MockObjectStorageClient
}

// NewMockObjectStorageClient creates a new mock instance.
func NewMockObjectStorageClient(ctrl *gomock.Controller) *MockObjectStorageClient {
	mock := &MockObjectStorageClient{ctrl: ctrl}
	mock.recorder = &MockObjectStorageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageClient) EXPECT() *MockObjectStorageClientMockRecorder {
	return m.recorder
}

// GetPreSignedUrlForPuttingObject mocks base method.
func (m *MockObjectStorageClient) GetPreSignedUrlForPuttingObject(objectKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreSignedUrlForPuttingObject", objectKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreSignedUrlForPuttingObject indicates an expected call of GetPreSignedUrlForPuttingObject.
func (mr *MockObjectStorageClientMockRecorder) GetPreSignedUrlForPuttingObject(objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreSignedUrlForPuttingObject", reflect.TypeOf((*MockObjectStorageClient)(nil).GetPreSignedUrlForPuttingObject), objectKey)
}
