// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_create_post is a generated GoMock package.
package mock_create_post

import (
	create_post "postservice/internal/features/create_post"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ConfirmCreatedPost mocks base method.
func (m *MockService) ConfirmCreatedPost(confirmPostData *create_post.ConfirmedCreatedPost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmCreatedPost", confirmPostData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmCreatedPost indicates an expected call of ConfirmCreatedPost.
func (mr *MockServiceMockRecorder) ConfirmCreatedPost(confirmPostData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmCreatedPost", reflect.TypeOf((*MockService)(nil).ConfirmCreatedPost), confirmPostData)
}

// CreatePost mocks base method.
func (m *MockService) CreatePost(post *create_post.Post) (string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", post)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockServiceMockRecorder) CreatePost(post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockService)(nil).CreatePost), post)
}
